name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Tests & Migrations"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install and Build
        run: |
          cd reactticket-core && npm install
          cd ../reactticket && npm install
          cd ../examples/demo-local && npm install && npm run build
      
      - name: Upload Sourcemaps to PostHog
        run: npx posthog-cli sourcemap upload --minified-urls "http*://*/assets/*" --sourcemap-dir ./examples/demo-local/dist/assets
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_PERSONAL_API_KEY }}
          POSTHOG_PROJECT_API_KEY: ${{ secrets.POSTHOG_PROJECT_API_KEY }}
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v2

      - name: Run Migrations
        run: npx supabase db push
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/demo-local/dist
