import { StorageAdapter } from '../types/adapter.types';
import { TicketTypeConfig, IssuedTicket, Order } from '../types/ticket.types';
import { PromoCode, PromoBatch } from '../types/promo.types';
import { ScanEvent } from '../types/scan.types';
import { ScanAccount } from '../types/scanAccount.types';
export declare class LocalStorageAdapter implements StorageAdapter {
    readonly name = "LocalStorageAdapter";
    private getStorageKey;
    getTicketTypes(eventId: string): Promise<TicketTypeConfig[]>;
    saveTicketType(eventId: string, type: TicketTypeConfig): Promise<void>;
    deleteTicketType(eventId: string, ticketTypeId: string): Promise<void>;
    createOrder(order: Order): Promise<void>;
    getOrder(orderId: string): Promise<Order | null>;
    private getAllOrders;
    updateOrderStatus(orderId: string, status: Order["status"]): Promise<void>;
    getTicket(ticketId: string): Promise<IssuedTicket | null>;
    getTicketsByOrder(orderId: string): Promise<IssuedTicket[]>;
    getIssuedTickets(eventId: string): Promise<IssuedTicket[]>;
    saveTicket(ticket: IssuedTicket): Promise<void>;
    saveTickets(newTickets: IssuedTicket[]): Promise<void>;
    updateTicketStatus(ticketId: string, status: IssuedTicket["status"]): Promise<void>;
    deliverTicket(ticketId: string, qrPayload: string): Promise<void>;
    transferTicket(ticketId: string, toEmail: string, newPersonalization: import('../types/ticket.types').TicketPersonalization): Promise<void>;
    countIssuedTickets(ticketTypeId: string, eventId: string): Promise<number>;
    getPromoCode(code: string): Promise<PromoCode | null>;
    savePromoBatch(batch: PromoBatch): Promise<void>;
    incrementPromoUsage(code: string): Promise<void>;
    listPromoBatches(): Promise<PromoBatch[]>;
    saveScanEvent(scan: ScanEvent): Promise<void>;
    getScanEvents(eventId: string): Promise<ScanEvent[]>;
    getScanAccount(accountId: string): Promise<ScanAccount | null>;
    getScanAccountByUsername(eventId: string, username: string): Promise<ScanAccount | null>;
    listScanAccounts(eventId: string): Promise<ScanAccount[]>;
    private listAllScanAccounts;
    saveScanAccount(account: ScanAccount): Promise<void>;
    updateScanAccount(accountId: string, patch: Partial<ScanAccount>): Promise<void>;
    deleteScanAccount(accountId: string): Promise<void>;
    incrementScanAccountLoginTimestamp(accountId: string, at: Date): Promise<void>;
}
